/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-01-26 15:27:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.file_005finclude;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/file_include/top.jspf", Long.valueOf(1674746640691L));
    _jspx_dependants.put("/file_include/header.jspf", Long.valueOf(1674746640691L));
    _jspx_dependants.put("/file_include/bottom.jspf", Long.valueOf(1674746640689L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	// ※ Service(비즈니스 로직)에서 실려왔다고 가정
	request.setAttribute("address", "종로구");
	pageContext.setAttribute("address", "도봉구");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>메인입니다...</title>\r\n");
      out.write("<!-- CDNs -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/9993903a39.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gugi&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th><a href=\"./main.jsp\">Home</a></th>\r\n");
      out.write("			<th><a href=\"./menu.jsp\">Menu</a></th>\r\n");
      out.write("			<th><a href=\"./navi.jsp\">Navigation</a></th>\r\n");
      out.write("			<th><a href=\"./chains.jsp\">Chains</a></th>\r\n");
      out.write("			<th><a href=\"./sitemap.jsp\">Site map</a></th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>side menu1</li>\r\n");
      out.write("					<li>side menu2</li>\r\n");
      out.write("					<li>side menu3</li>\r\n");
      out.write("					<li>side menu4</li>\r\n");
      out.write("					<li>side menu5</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</th>\r\n");
      out.write("			<th colspan=\"4\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<h1 style=\"font-family: 'Montserrat', sans-serif; font-weight: 900;\">main.jsp</h1>\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"fa-3x\">\r\n");
      out.write("  		<i class=\"fa-solid fa-snowboarding\"></i>\r\n");
      out.write("    	<i class=\"fa-solid fa-snowboarding fa-rotate-90\"></i>\r\n");
      out.write("    	<i class=\"fa-solid fa-snowboarding fa-rotate-180\"></i>\r\n");
      out.write("    	<i class=\"fa-solid fa-snowboarding fa-rotate-270\"></i>\r\n");
      out.write("    	<i class=\"fa-solid fa-snowboarding fa-flip-horizontal\"></i>\r\n");
      out.write("    	<i class=\"fa-solid fa-snowboarding fa-flip-vertical\"></i>\r\n");
      out.write("    	<i class=\"fa-solid fa-snowboarding fa-flip-both\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("	<p style=\"font-family: 'Montserrat', sans-serif; font-weight: 400;\">Like your own personal Font Awesome CDN</p>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("			</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"5\">\r\n");
      out.write("				대표이사 : 안병현 | ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" | 사업자등록번호 : 102-81-11670\r\n");
      out.write("				대표전화 : 1544-1900(발신자 부담전화) | FAX : 0502-987-5711(지역번호 공통) | 서울특별시 통신판매업신고번호 : 제 653호 사업자정보확인\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
